[workspace]
resolver = "3"
members = ["egui_json_tree", "demo"]

[workspace.package]
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
authors = ["Duncan MacKinnon <dmackdev@gmail.com>"]
repository = "https://github.com/dmackdev/egui_json_tree"

[workspace.dependencies]
egui = { version = "0.36", default-features = false }
eframe = "0.36"
egui_kittest = "0.36"
serde_json = { version = "1" }
