name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      - name: Build
        run: cargo build --locked --workspace
      - name: Test
        run: cargo test --locked
      - name: Test json_tree_test for simd_json feature
        run: cargo test --locked --features=simd_json --no-default-features --test json_tree_test
      - name: Clippy
        run: cargo clippy
      - name: Format
        run: cargo fmt --all -- --check

  web-demo:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0
      - uses: jetli/trunk-action@1346cc09eace4beb84e403e199a471346d4684c9 # v0.5.1
        with:
          version: "v0.21.14"
      - name: Trunk build
        working-directory: demo
        run: trunk build --locked --release --public-url /egui_json_tree
      - name: Maybe deploy web demo
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        with:
          build_dir: demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
